function [scenario, egoVehicle] = beeeeeeeee()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 05-Mar-2024 04:38:51

% Construct a drivingScenario object.
scenario = drivingScenario;
plot(scenario)
% Add all road segments
roadCenters = [2.2 -0.5 0;
               54.9 0.6 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [5.2 -0.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [5.2 -0.1 0;
             52.3 0.7 0];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

